application.data-dir: ${DATA_DIR:inventory-api}
server.port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/inventory
    username: root
    password: root123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
